/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_lmc_ipcservice_MainActivity */

#ifndef _Included_com_android_lmc_ipcservice_MainActivity
#define _Included_com_android_lmc_ipcservice_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_lmc_ipcservice_MainActivity
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_lmc_ipcservice_MainActivity_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
